### ISSUE TITLE
!!pairs is not correctly ordered

### ISSUE THREAD

**Issue by autermann** [autermann/yaml#1]
``` java
YamlNodeFactory.getDefault().pairsNode()
        .put("a", "a")
        .put("b", "b")
        .put("a", "a")
        .dump(System.out);
```

will result in:

``` yaml
!!pairs
a: a
a: a
b: b
```
